build-package new release: sex 21 mar 2025 11:00:50 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/pkgbuild/pkgbuild.install b/pkgbuild/pkgbuild.install
--- a/pkgbuild/pkgbuild.install
+++ b/pkgbuild/pkgbuild.install
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
 # -*- coding: utf-8 -*-
+# shellcheck source=/dev/null
 
 export TERM=${TERM:-xterm}
 export TERM=${TERM:-xterm-256color}
@@ -13,24 +14,105 @@ export blue="\033[1;34m"
 export magenta="\033[1;35m"
 export cyan="\033[1;36m"
 export white="\033[1;37m"
-
-# Setting variables for bold and reset
 export bold="\033[1m"
 export reset="\033[0m"
+#
+export COL_NC='\e[0m' # No Color
+export COL_LIGHT_GREEN='\e[1;32m'
+export COL_LIGHT_RED='\e[1;31m'
+export TICK="${white}[${COL_LIGHT_GREEN}✓${COL_NC}${white}]"
+export CROSS="${white}[${COL_LIGHT_RED}✗${COL_NC}${white}]"
+export INFO="[i]"
+export DONE="${COL_LIGHT_GREEN} done!${COL_NC}"
+export OVER="\\r\\033[K"
+export DOTPREFIX="  ${black}::${reset} "
+######################################################################################################
+# configurações básicas (NÃO alterar a ordem)
+declare IS_UPGRADE=false                          # não alterar
+declare DM='lxdm'                                 # Display Manager/Login Manager
+declare WM='wmaker'                               # nome meta package
+declare pkgname=comm-"${WM}"                      # não alterar
+declare servicesToEnable=("${DM}" sshd bluetooth) # insira aqui serviços a serem ATIVADOS
+declare servicesToDisable=(lightdm sddm gdm)      #insira aqui os serviços a serem DESATIVADOS
+######################################################################################################
 
 msg() {
 	local msg="$1"
-	echo -e "${green}==>[comm-wmaker] ${bold}${yellow}${msg}${reset}" >&2
+	echo -e "${green}==>[${pkgname}] ${bold}${yellow}${msg}${reset}" >&2
+}
+
+log_ok() { echo -e "  ${TICK} ${*}${reset}"; }
+log_err() { echo -e "  ${CROSS} ${*}${reset}"; }
+
+die() {
+	local msg=$1
+	shift
+	#printf "  %b %s\\n" "${CROSS}" "${red}${msg}${reset}"
+	echo -e "  ${CROSS} ${red}${msg}${reset}"
+	sh_restoring_lock
+	exit 1
+}
+
+sh_load_optdepends() {
+	local info_file="/usr/share/${pkgname}/optdepends"
+
+	if [[ -f "$info_file" && -r "$info_file" ]]; then
+		mapfile -t OPTDEPENDS <"$info_file"
+	else
+		msg "${red}FATAL: Something went wrong! File '$info_file' not found or without read permission."
+		msg "${red}FATAL: Something went wrong! File '$info_file' not found or without read permission."
+	fi
+}
+
+sh_restoring_lock() {
+	msg "Restauring pacman lock: /var/lib/pacman/db.lck"
+	touch /var/lib/pacman/db.lck &>/dev/null
+}
+
+sh_check_package_exist() {
+	local pkg
+	for pkg in "${OPTDEPENDS[@]}"; do
+		if ! pacman -Qs "$pkg" &>/dev/null; then
+			if ! pacman -Ss "^$pkg$" &>/dev/null; then
+				die "Fatal: package '$pkg' not exist in repo"
+			fi
+		fi
+		log_ok "Check: ${cyan}$pkg"
+	done
+}
+
+sh_start_dbus_in_chroot() {
+	# Verifica se o D-Bus já está em execução
+	if ! pgrep -x "dbus-daemon" >/dev/null; then
+		# Cria o diretório para o socket do D-Bus
+		mkdir -p /run/dbus
+		chmod 755 /run/dbus
+
+		# Inicia o D-Bus
+		dbus-daemon --system --fork
+
+		# Configura as variáveis de ambiente
+		export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
+		export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
+	fi
 }
 
 post_install() {
-	msg "Initializing system configuration..."
+	msg "Initializing system installation and configuration..."
+
+	sh_load_optdepends
 
 	[[ -e /etc/environment ]] && source /etc/environment
 	: "${IN_CHROOT_INSTALLER:=false}"
 	: "${IN_CHROOT_INSTALLER_USER:=root}"
 
+	if $IN_CHROOT_INSTALLER; then
+		# sh_start_dbus_in_chroot
+		:
+	fi
+
 	if [[ -f /var/lib/pacman/db.lck ]]; then
+		msg "Removing pacman lock: /var/lib/pacman/db.lck"
 		rm -f /var/lib/pacman/db.lck &>/dev/null
 	fi
 
@@ -43,12 +125,27 @@ post_install() {
 		lib32-vulkan-mesa-layers
 	)
 
-	install_packages() {
-		pacman -S --quiet --noconfirm --needed --overwrite \* "$@" &>/dev/null
+	synchronizing_database() {
+		#pacman -Syu --quiet --noconfirm 1>/dev/null
+		pacman -Sy --quiet --noconfirm &>/dev/null
 	}
+
+	install_packages() {
+		#    pacman -S --quiet --noconfirm --needed --overwrite \* "$@" &>/dev/null
+		pacman -S --quiet --noconfirm --needed --overwrite \* "$@" 1>/dev/null
+	}
+
+	msg "Please wait, synchronizing databases..."
+	synchronizing_database
 
 	msg "Installing common packages: ${COMMON_PACKAGES[*]}"
 	install_packages "${COMMON_PACKAGES[@]}"
+
+	msg "Checking for the existence of packages..."
+	sh_check_package_exist
+
+	msg "Installing optdepends packages: ${OPTDEPENDS[*]}"
+	install_packages "${OPTDEPENDS[@]}"
 
 	msg "Detecting GPU and installing appropriate drivers..."
 	GPU_INFO=$(lspci -nnk | grep -A3 -E "VGA|3D|Display")
@@ -84,30 +181,24 @@ EOF
 		msg "${yellow}Warning: No compatible GPU detected. Skipping driver installation.${reset}"
 	fi
 
-	msg "Create the 'lxdm' user if it doesn't exist"
-	if ! id "lxdm" >/dev/null; then
-		msg "Creating Lxdm user..."
-		useradd -r -s /usr/bin/nologin -M -d /var/lib/lxdm lxdm &>/dev/null
+	msg "Create the ${DM^} user if it doesn't exist"
+	if ! id "${DM}" >/dev/null; then
+		msg "Creating ${DM^} user..."
+		useradd -r -s /usr/bin/nologin -M -d /var/lib/${DM} ${DM} &>/dev/null
 	else
-		msg "Lxdm user already exists, skipping creation."
+		msg "${DM^} user already exists, skipping creation."
 	fi
 
-	# Ensure Lxdm directory exists with correct permissions
-	msg "Setting up Lxdm directory..."
-	mkdir -p /var/lib/lxdm >/dev/null
-	chown -R lxdm:lxdm /var/lib/lxdm >/dev/null
-
-	msg "Enabling Lxdm..."
-	if ! systemctl enable lxdm &>/dev/null; then
-    msg "${red}Error: It went wrong when activating lxdm"
-	fi
+	msg "Setting up ${DM^} directory..."
+	mkdir -p /var/lib/${DM} >/dev/null
+	chown -R ${DM}:${DM} /var/lib/${DM} >/dev/null
 
 	msg "Setting up user..."
 	user=$(awk -F: '$3 >= 1000 && $3 < 65000 { print $1; exit }' /etc/passwd)
 	if $IN_CHROOT_INSTALLER; then
 		if [[ -n $IN_CHROOT_INSTALLER_USER || $IN_CHROOT_INSTALLER_USER != 'root' ]]; then
-  		user=$IN_CHROOT_INSTALLER_USER
-    fi
+			user=$IN_CHROOT_INSTALLER_USER
+		fi
 	fi
 	user_home=$(getent passwd "$user" | cut -d: -f6)
 
@@ -115,39 +206,84 @@ EOF
 	mkdir -p "$user_home" &>/dev/null
 	cp -Rfpa /etc/skel/. "$user_home/" &>/dev/null
 
-  msg "Setting user folder permissions in ${user_home}"
+	msg "Setting user folder permissions in ${user_home}"
 	chown -R "$user:$user" "$user_home" &>/dev/null
 
-	msg "Configuring Nautilus..."
-	if glib-compile-schemas /usr/share/glib-2.0/schemas/; then
-		msg "Nautilus schemas compiled successfully!"
-	else
-		msg "${yellow}Warning: Failed to compile Nautilus schemas. Some features may not work correctly.${reset}"
+	if command -v nautilus >/dev/null; then
+		msg "Configuring Nautilus..."
+		if glib-compile-schemas /usr/share/glib-2.0/schemas/; then
+			msg "Nautilus schemas compiled successfully!"
+		else
+			msg "${yellow}Warning: Failed to compile Nautilus schemas. Some features may not work correctly.${reset}"
+		fi
 	fi
 
+	if ! $IS_UPGRADE; then
+		msg "Enabling ${DM^}..."
+		if ! systemctl enable ${DM} 1>/dev/null; then
+			msg "${red}Error: It went wrong when activating ${DM^}"
+		fi
+	fi
+
+	for service in "${servicesToDisable[@]}"; do
+		if systemctl is-active --quiet "${service}"; then
+			msg "Disabling service ${service}..."
+			if ! systemctl disable "${service}" &>/dev/null; then
+				msg "${red}Error: It went wrong when desactivating service ${service}"
+			fi
+		else
+			msg "${green}Service ${service} is already inactive..."
+			continue
+		fi
+	done
+
+	for service in "${servicesToEnable[@]}"; do
+		if systemctl is-active --quiet "${service}"; then
+			msg "${green}Service ${service} is already active..."
+			continue
+		else
+			if ! systemctl enable "${service}" &>/dev/null; then
+				msg "${red}Error: It went wrong when activating service ${service}"
+			fi
+		fi
+	done
+
 	if ! $IN_CHROOT_INSTALLER; then
-		msg "Please wait, Generating initramfs for all kernels..."
-		mkinitcpio -P &>/dev/null
+		if ! $IS_UPGRADE; then
+			msg "Please wait, Generating initramfs for all kernels..."
+			mkinitcpio -P &>/dev/null
+		fi
 
 		msg "Configuring GRUB..."
 		# Change GRUB config
-		sed -i 's|^GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT="quiet splash plymouth.enable=1 loglevel=4 libata.noacpi=1 acpi=force apm=power-off nowatchdog tsc=nowatchdog cryptomgr.notests no_timer_check rcupdate.rcu_expedited=1 intel_pstate=active amd_pstate=active cpuidle.governor=teo split_lock_detect=off clearcpuid=514 transparent_hugepage=never skew_tick=1 intremap=off nosoftlockup audit=0 nomce systemd.show_status=auto rd.udev.log_level=3 apparmor=1 security=apparmor vconsole.font=Uni2-Fixed16 intel_iommu=on amd_iommu=on tdx=on nvme_load=yes nouveau.modeset=1 i915.modeset=1 amdgpu.modeset=1 radeon.si_support=0 radeon.cik_support=0 amdgpu.si_support=1 amdgpu.cik_support=1 nvidia.modeset=1 nvidia_drm.modeset=1 DEEPIN_GFXMODE="|' /etc/default/grub >/dev/null
+		if ! grep -qi "${WM}" /etc/default/grub; then
+			sed -i "s/^GRUB_DISTRIBUTOR=\"\(.*\)\"/GRUB_DISTRIBUTOR=\"\1 ${WM^}\"/" /etc/default/grub
+		fi
+		sed -i 's|^GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT="quiet splash plymouth.enable=1 loglevel=4 libata.noacpi=1 acpi=force apm=power-off nowatchdog tsc=nowatchdog cryptomgr.notests no_timer_check rcupdate.rcu_expedited=1 intel_pstate=active amd_pstate=active cpuidle.governor=teo split_lock_detect=off clearcpuid=514 transparent_hugepage=never skew_tick=1 intremap=off nosoftlockup audit=0 nomce systemd.show_status=auto rd.udev.log_level=3 apparmor=1 security=apparmor vconsole.font=Uni2-Fixed16 intel_iommu=on amd_iommu=on tdx=on nvme_load=yes nouveau.modeset=1 i915.modeset=1 amdgpu.modeset=1 radeon.si_support=0 radeon.cik_support=0 amdgpu.si_support=1 amdgpu.cik_support=1 nvidia.modeset=1 nvidia_drm.modeset=1 DEEPIN_GFXMODE="|' /etc/default/grub 1>/dev/null
 
 		msg "Generating GRUB configuration files..."
 		update-grub &>/dev/null
 	fi
 
-	msg "Installation complete. Rebooting in 10 seconds..."
-	# Countdown before reboot
-	for i in $(seq 10 -1 1); do
-		printf "%d..." "$i"
-		sleep 1
-	done
-	echo
-	msg "Rebooting now..."
-	reboot
+	# Restauring pacman lock: /var/lib/pacman/db.lck
+	sh_restoring_lock
+
+	if ! $IS_UPGRADE; then
+		msg "Installation complete. Rebooting in 10 seconds..."
+		# Countdown before reboot
+		for i in $(seq 10 -1 1); do
+			printf "%d..." "$i"
+			sleep 1
+		done
+		echo
+		msg "Rebooting now..."
+		reboot
+	else
+		msg "Upgrade complete."
+	fi
 }
 
 post_upgrade() {
+	IS_UPGRADE=true
 	post_install
 }
